/* C7c-b2 integrated reverse-time material-gradient MPI harness. */
#define main m63c_locked_c5a_harness_main
#include "m63c_full_state_step_harness.c"
#undef main

int INVMAT1;

float **matrix(int nrl,int nrh,int ncl,int nch){int row,rows=nrh-nrl+1,cols=nch-ncl+1;float **base=(float **)malloc((size_t)rows*sizeof(float *));float *data=(float *)calloc((size_t)rows*cols,sizeof(float));float **view;if(base==NULL||data==NULL)MPI_Abort(MPI_COMM_WORLD,801);view=base-nrl;for(row=nrl;row<=nrh;++row)view[row]=data+(row-nrl)*cols-ncl;return view;}
void free_matrix(float **m,int nrl,int nrh,int ncl,int nch){(void)nrh;(void)nch;free(m[nrl]+ncl);free(m+nrl);}
void err(char text[]){fprintf(stderr,"%s\n",text);MPI_Abort(MPI_COMM_WORLD,802);}

static double field_difference(const struct field *a,const struct field *b){double n=0.0,d=0.0,x;int k;for(k=0;k<a->nrows*a->ncols;++k){x=(double)a->data[k]-b->data[k];n+=x*x;d+=(double)b->data[k]*b->data[k];}return sqrt(n/fmax(d,1e-300));}
static double volume_difference(const struct volume *a,const struct volume *b){double n=0.0,d=0.0,x;int i,j,l;for(j=a->rmin;j<=a->rmax;++j)for(i=a->cmin;i<=a->cmax;++i)for(l=1;l<=a->mechanisms;++l){x=(double)a->v[j][i][l]-b->v[j][i][l];n+=x*x;d+=(double)b->v[j][i][l]*b->v[j][i][l];}return sqrt(n/fmax(d,1e-300));}
static double state_difference(const struct owned_state *a,const struct owned_state *b){double m=0.0;m=fmax(m,field_difference(&a->vz,&b->vz));m=fmax(m,field_difference(&a->sxz,&b->sxz));m=fmax(m,field_difference(&a->syz,&b->syz));m=fmax(m,volume_difference(&a->r,&b->r));m=fmax(m,volume_difference(&a->q,&b->q));if(FW){m=fmax(m,field_difference(&a->psi_sxz_x,&b->psi_sxz_x));m=fmax(m,field_difference(&a->psi_syz_y,&b->psi_syz_y));m=fmax(m,field_difference(&a->psi_vzx,&b->psi_vzx));m=fmax(m,field_difference(&a->psi_vzy,&b->psi_vzy));}return m;}
static void forward_step(struct owned_state *s,int nt,float **src,float **signals,struct field diag[6],struct field *dummy,struct field *rhoi,struct field *fx,struct field *fy,struct volume *dip,struct volume *d,struct volume *pp,float *hc,float *bip,float *bjm,float *cip,float *cjm,float *K,float *Kh,float *a,float *ah,float *b,float *bh,float **bl,float **br,float **bt,float **bb,MPI_Request *req){update_v_PML_SH(1,NX,1,NY,nt,s->view.vz,diag[0].v,diag[1].v,diag[2].v,s->view.sxz,s->view.syz,dummy->v,rhoi->v,src,signals,1,dummy->v,hc,0,0,0,K,a,b,Kh,ah,bh,K,a,b,Kh,ah,bh,s->view.psi_sxz_x,s->view.psi_syz_y);exchange_v_SH(s->view.vz,bl,br,bt,bb,req,req);if(FREE_SURF&&POS[2]==0)surface_elastic_SH_velocity(s->view.vz,NX,FDORDER/2);update_s_visc_PML_SH(1,NX,1,NY,s->view.vz,diag[3].v,diag[4].v,s->view.syz,s->view.sxz,dummy->v,dummy->v,dummy->v,hc,0,s->view.r,pp->v,s->view.q,fx->v,fy->v,dummy->v,bip,bjm,cip,cjm,d->v,pp->v,dip->v,K,a,b,Kh,ah,bh,K,a,b,Kh,ah,bh,s->view.psi_vzx,s->view.psi_vzy,NULL,0);if(FREE_SURF&&POS[2]==0)surface_elastic_SH_stress(s->view.syz,NX,FDORDER/2);exchange_s_SH(s->view.sxz,s->view.syz,bl,br,bt,bb,req,req);}

struct dgrad_field { double **v, **rows, *data; };
static struct dgrad_field dg_new(void){struct dgrad_field f;int j;f.rows=(double **)calloc((size_t)NY+2,sizeof(double *));f.data=(double *)calloc((size_t)(NX+2)*(NY+2),sizeof(double));if(!f.rows||!f.data)MPI_Abort(MPI_COMM_WORLD,801);f.v=f.rows;for(j=0;j<=NY+1;++j)f.v[j]=f.data+(size_t)j*(NX+2);return f;}
static void dg_free(struct dgrad_field *f){free(f->data);free(f->rows);}
static double fchecksum(const struct field *f){double s=0.0;int k;for(k=0;k<f->nrows*f->ncols;++k)s+=(k+1)*(double)f->data[k];return s;}
static double trajectory_checksum(const struct visco_sh_material_observable_trajectory *t){double s=0.0;int n,i,j,k=0;for(n=0;n<t->nsteps;++n)for(j=1;j<=t->ny;++j)for(i=1;i<=t->nx;++i){++k;s+=k*((double)t->steps[n].qsum[j][i]+2.0*t->steps[n].strain_x[j][i]+3.0*t->steps[n].strain_y[j][i]);}return s;}
static double grad_difference(const struct field *a,const struct field *b){double num=0.0,den=0.0,d;int k;for(k=0;k<a->nrows*a->ncols;++k){d=(double)a->data[k]-b->data[k];num+=d*d;den+=(double)b->data[k]*b->data[k];}return sqrt(num/fmax(den,1.0e-300));}
static double owned_gradient_checksum(const struct field *a,const struct field *b,const struct field *c){double s=0.0;int i,j,k=0;for(j=1;j<=NY;++j)for(i=1;i<=NX;++i){++k;s+=k*((double)a->v[j][i]+2.0*b->v[j][i]+3.0*c->v[j][i]);}return s;}
static void fill_material(int rank,int invmat,struct q_tau_mapping *mapping,struct field *primary,struct field *rho,struct field *q,struct field *tau,struct field *rhoi,struct field *mu_x,struct field *mu_y,struct field *tau_x,struct field *tau_y,struct field *fipjp,struct field *f,struct volume *dip,struct volume *d,float *eta,float *bip,float *bjm,float *cip,float *cjm,double reference_sum){int i,j,l;for(j=primary->rmin;j<=primary->rmax;++j)for(i=primary->cmin;i<=primary->cmax;++i){rho->v[j][i]=(float)(2150.0+7.0*rank+2.5*i+1.7*j);primary->v[j][i]=(float)(invmat==1?1450.0+3.1*i+2.2*j+4.0*rank:4.65e9+1.2e6*i+0.8e6*j+2.0e6*rank);q->v[j][i]=(float)(24.0+1.3*rank+0.31*i+0.27*j);rhoi->v[j][i]=1.0f/rho->v[j][i];tau->v[j][i]=q_to_tau(q->v[j][i],mapping);}matcopy_SH(rho->v,primary->v,tau->v);av_mu_SH(primary->v,mu_x->v,mu_y->v,rho->v);av_tau(tau->v,tau_x->v);for(j=1;j<=NY;++j)for(i=1;i<=NX;++i){double rx,ry;tau_y->v[j][i]=tau->v[j][i];rx=mu_x->v[j][i]/(1.0+reference_sum*tau_x->v[j][i]);ry=mu_y->v[j][i]/(1.0+reference_sum*tau_y->v[j][i]);fipjp->v[j][i]=(float)(DT*rx*(1.0+L*tau_x->v[j][i]));f->v[j][i]=(float)(DT*ry*(1.0+L*tau_y->v[j][i]));for(l=1;l<=L;++l){dip->v[j][i][l]=(float)(rx*eta[l]*tau_x->v[j][i]);d->v[j][i][l]=(float)(ry*eta[l]*tau_y->v[j][i]);}}for(l=1;l<=L;++l){bip[l]=bjm[l]=1.0f/(1.0f+0.5f*eta[l]);cip[l]=cjm[l]=1.0f-0.5f*eta[l];}}
static void select_steps(struct visco_sh_material_observable_trajectory *t,const char *mode){int n,i,j,mid=t->nsteps/2;if(!strcmp(mode,"all"))return;for(n=0;n<t->nsteps;++n)if((!strcmp(mode,"first")&&n!=0)||(!strcmp(mode,"middle")&&n!=mid)||(!strcmp(mode,"last")&&n!=t->nsteps-1)||(!strcmp(mode,"cancel")&&n>1))for(j=1;j<=t->ny;++j)for(i=1;i<=t->nx;++i)t->steps[n].qsum[j][i]=t->steps[n].strain_x[j][i]=t->steps[n].strain_y[j][i]=0.0f;if(!strcmp(mode,"cancel")&&t->nsteps>1)for(j=1;j<=t->ny;++j)for(i=1;i<=t->nx;++i){t->steps[1].qsum[j][i]=-t->steps[0].qsum[j][i];t->steps[1].strain_x[j][i]=-t->steps[0].strain_x[j][i];t->steps[1].strain_y[j][i]=-t->steps[0].strain_y[j][i];}for(n=0;n<t->nsteps;++n)for(j=1;j<=t->ny;++j)for(i=1;i<=t->nx;++i){if(!strcmp(mode,"rho_only"))t->steps[n].strain_x[j][i]=t->steps[n].strain_y[j][i]=0.0f;if(!strcmp(mode,"x_only"))t->steps[n].qsum[j][i]=t->steps[n].strain_y[j][i]=0.0f;if(!strcmp(mode,"y_only"))t->steps[n].qsum[j][i]=t->steps[n].strain_x[j][i]=0.0f;}}

int main(int argc,char **argv){
 struct owned_state input,forward_state,dual,fixed_terminal,fixed_initial,fixed_scratch,mat_terminal,mat_initial,mat_scratch,ref_terminal,ref_initial,ref_scratch;
 struct field rhoi,fipjp,f,primary,rho,q,tau,mu_x,mu_y,tau_x,tau_y,gp,gr,gq,rp,rr,rq,diag[6],dummy;struct volume dip,d,pp;struct visco_sh_full_step_config cfg,step_cfg;struct visco_sh_material_observable_trajectory trajectory;struct visco_sh_reverse_time_material_context material;struct visco_sh_material_adjoint_step_context step_material;struct q_tau_mapping mapping;struct dgrad_field temp[5];struct visco_sh_native_material_gradient_fields temp_native;struct visco_sh_material_timestep_vjp_output *series,*sum;float *hc,*bip,*bjm,*cip,*cjm,*eta,*K,*Kh,*a,*ah,*b,*bh,*frequencies;float **srcpos,**signals,*src_storage,*signal_storage,**bl,**br,**bt,**bb,*sl,*sr,*st,*sb;double *bar_receiver,*fixed_signal,*mat_signal,*ref_signal;MPI_Request request[4];int rank,size,npx,npy,nsteps,invmat,qmode,fs,fw,h,i,j,l,k,n,status,rec_x[1],rec_y[1],src_x[1],src_y[1],src_type[1],point,owned;double refsum=0.0,state_error,signal_error,gradient_error,input_before,input_after,gradient_checksum;void *bsend;int bsize=1<<20;const char *mode;
 MPI_Init(&argc,&argv);MPI_Comm_rank(MPI_COMM_WORLD,&rank);MPI_Comm_size(MPI_COMM_WORLD,&size);MYID=rank;FP=stderr;if(argc!=10)MPI_Abort(MPI_COMM_WORLD,802);npx=atoi(argv[1]);npy=atoi(argv[2]);nsteps=atoi(argv[3]);invmat=atoi(argv[4]);qmode=atoi(argv[5]);fs=atoi(argv[6]);fw=atoi(argv[7]);mode=argv[8];if(size!=npx*npy)MPI_Abort(MPI_COMM_WORLD,803);NPROCX=npx;NPROCY=npy;NX=10;NY=12;FDORDER=4;L=2;FW=fw;FREE_SURF=fs;BOUNDARY=0;INVMAT1=invmat;DT=0.0013f;DH=7.5f;topology(rank);h=2;bsend=malloc((size_t)bsize);MPI_Buffer_attach(bsend,bsize);
 input=state_new(h,FW,L);forward_state=state_new(h,FW,L);dual=state_new(h,FW,L);fixed_terminal=state_new(h,FW,L);fixed_initial=state_new(h,FW,L);fixed_scratch=state_new(h,FW,L);mat_terminal=state_new(h,FW,L);mat_initial=state_new(h,FW,L);mat_scratch=state_new(h,FW,L);ref_terminal=state_new(h,FW,L);ref_initial=state_new(h,FW,L);ref_scratch=state_new(h,FW,L);state_initialize(&input,rank,0,FW,L);state_initialize(&dual,rank,1,FW,L);state_copy(&forward_state,&input,FW);state_copy(&fixed_terminal,&dual,FW);state_copy(&mat_terminal,&dual,FW);state_copy(&ref_terminal,&dual,FW);
#define FN(x) x=field_new(-h,NY+h+1,1-h,NX+h)
 FN(rhoi);FN(fipjp);FN(f);FN(primary);FN(rho);FN(q);FN(tau);FN(mu_x);FN(mu_y);FN(tau_x);FN(tau_y);FN(gp);FN(gr);FN(gq);FN(rp);FN(rr);FN(rq);FN(dummy);dip=volume_new(-h,NY+h+1,1-h,NX+h,L);d=volume_new(-h,NY+h+1,1-h,NX+h,L);pp=volume_new(-h,NY+h+1,1-h,NX+h,L);for(k=0;k<6;++k)diag[k]=field_new(-h,NY+h+1,1-h,NX+h);
 hc=(float *)calloc(3,sizeof(float));hc[1]=1.0f;hc[2]=-0.041f;bip=(float *)calloc(3,sizeof(float));bjm=(float *)calloc(3,sizeof(float));cip=(float *)calloc(3,sizeof(float));cjm=(float *)calloc(3,sizeof(float));eta=(float *)calloc(3,sizeof(float));frequencies=(float *)calloc(3,sizeof(float));frequencies[1]=4.0f;frequencies[2]=9.0f;init_q_tau_mapping(&mapping,qmode,L,frequencies,2.0f,18.0f,0.5f);for(l=1;l<=L;++l){double theta=1.0/(2.0*PI*frequencies[l]),x=2.0*PI*6.0*theta;eta[l]=(float)(DT/theta);refsum+=x*x/(1.0+x*x);}fill_material(rank,invmat,&mapping,&primary,&rho,&q,&tau,&rhoi,&mu_x,&mu_y,&tau_x,&tau_y,&fipjp,&f,&dip,&d,eta,bip,bjm,cip,cjm,refsum);
 K=(float *)calloc((size_t)2*FW+1,sizeof(float));Kh=(float *)calloc((size_t)2*FW+1,sizeof(float));a=(float *)calloc((size_t)2*FW+1,sizeof(float));ah=(float *)calloc((size_t)2*FW+1,sizeof(float));b=(float *)calloc((size_t)2*FW+1,sizeof(float));bh=(float *)calloc((size_t)2*FW+1,sizeof(float));for(k=1;k<=2*FW;++k){K[k]=1.11f;Kh[k]=1.08f;a[k]=-0.031f;ah[k]=-0.027f;b[k]=0.82f;bh[k]=0.84f;}srcpos=buffer_new(8,1,&src_storage);signals=buffer_new(1,nsteps,&signal_storage);srcpos[1][1]=(float)(3+rank%2);srcpos[2][1]=(float)(4+rank%3);srcpos[8][1]=1.0f;for(n=0;n<nsteps;++n)signals[1][n+1]=(float)(0.021+0.003*rank+0.0017*n);bl=buffer_new(NY,2*(h+1),&sl);br=buffer_new(NY,2*(h+1),&sr);bt=buffer_new(NX,2*(h+1),&st);bb=buffer_new(NX,2*(h+1),&sb);
 memset(&trajectory,0,sizeof(trajectory));if(visco_sh_material_observable_trajectory_init(&trajectory,NX,NY,nsteps,1,FW,FREE_SURF,BOUNDARY,NPROCX,NPROCY)!=0)MPI_Abort(MPI_COMM_WORLD,804);for(n=0;n<nsteps;++n){visco_sh_material_observable_begin_step(&trajectory,n);forward_step(&forward_state,n+1,srcpos,signals,diag,&dummy,&rhoi,&fipjp,&f,&dip,&d,&pp,hc,bip,bjm,cip,cjm,K,Kh,a,ah,b,bh,bl,br,bt,bb,request);visco_sh_material_observable_end_step();}select_steps(&trajectory,mode);
 bar_receiver=(double *)calloc((size_t)nsteps,sizeof(double));fixed_signal=(double *)calloc((size_t)nsteps,sizeof(double));mat_signal=(double *)calloc((size_t)nsteps,sizeof(double));ref_signal=(double *)calloc((size_t)nsteps,sizeof(double));for(n=0;n<nsteps;++n)bar_receiver[n]=-0.17+0.019*rank-0.0023*n;rec_x[0]=6+rank%3;rec_y[0]=5+rank%2;src_x[0]=(int)srcpos[1][1];src_y[0]=(int)srcpos[2][1];src_type[0]=1;memset(&cfg,0,sizeof(cfg));cfg.nx=NX;cfg.ny=NY;cfg.fdorder=FDORDER;cfg.mechanisms=L;cfg.fw=FW;cfg.free_surface=FREE_SURF;cfg.boundary=BOUNDARY;memcpy(cfg.pos,POS,sizeof(POS));memcpy(cfg.index,INDEX,sizeof(INDEX));cfg.nproc_x=NPROCX;cfg.nproc_y=NPROCY;cfg.dt=DT;cfg.dh=DH;cfg.hc=hc;cfg.rhoi=rhoi.v;cfg.fipjp=fipjp.v;cfg.f=f.v;cfg.bip=bip;cfg.bjm=bjm;cfg.cip=cip;cfg.cjm=cjm;cfg.dip=dip.v;cfg.d=d.v;cfg.K_x=K;cfg.a_x=a;cfg.b_x=b;cfg.K_x_half=Kh;cfg.a_x_half=ah;cfg.b_x_half=bh;cfg.K_y=K;cfg.a_y=a;cfg.b_y=b;cfg.K_y_half=Kh;cfg.a_y_half=ah;cfg.b_y_half=bh;cfg.nrec=1;cfg.rec_x=rec_x;cfg.rec_y=rec_y;cfg.nsrc=1;cfg.src_x=src_x;cfg.src_y=src_y;cfg.source_type=src_type;cfg.comm=MPI_COMM_WORLD;
 memset(&material,0,sizeof(material));material.trajectory=&trajectory;material.mu_x=mu_x.v;material.tau_x=tau_x.v;material.mu_y=mu_y.v;material.tau_y=tau_y.v;material.reference_sum=refsum;material.eta_x=eta;material.eta_y=eta;material.invmat1=invmat;material.mapping=&mapping;material.primary_post=primary.v;material.rho_post=rho.v;material.owned_q=q.v;material.grad_primary=gp.v;material.grad_rho=gr.v;material.grad_q=gq.v;input_before=trajectory_checksum(&trajectory)+fchecksum(&primary)+fchecksum(&rho)+fchecksum(&q)+fchecksum(&rhoi)+fchecksum(&mu_x)+fchecksum(&mu_y)+fchecksum(&tau_x)+fchecksum(&tau_y)+fchecksum(&fipjp)+fchecksum(&f);for(n=0;n<nsteps;++n)input_before+=(n+1)*bar_receiver[n];
 if(!strncmp(mode,"invalid_",8)){double unchanged;const struct visco_sh_reverse_time_material_context *material_arg=&material;for(j=1;j<=NY;++j)for(i=1;i<=NX;++i)gp.v[j][i]=gr.v[j][i]=gq.v[j][i]=77.0f;for(n=0;n<nsteps;++n)mat_signal[n]=31.0+n;if(!strcmp(mode,"invalid_nsteps"))trajectory.nsteps=nsteps+1;if(!strcmp(mode,"invalid_nx"))trajectory.nx=NX+1;if(!strcmp(mode,"invalid_ny"))trajectory.ny=NY+1;if(!strcmp(mode,"invalid_dtinv"))trajectory.dtinv=2;if(!strcmp(mode,"invalid_missing"))material.mapping=NULL;if(!strcmp(mode,"invalid_context"))material_arg=NULL;status=visco_sh_reverse_time_adjoint_material(&cfg,nsteps,bar_receiver,&mat_terminal.view,&mat_initial.view,&mat_scratch.view,mat_signal,material_arg);unchanged=state_difference(&mat_terminal,&ref_terminal);for(j=1;j<=NY;++j)for(i=1;i<=NX;++i)unchanged=fmax(unchanged,fabs(gp.v[j][i]-77.0)+fabs(gr.v[j][i]-77.0)+fabs(gq.v[j][i]-77.0));for(n=0;n<nsteps;++n)unchanged=fmax(unchanged,fabs(mat_signal[n]-(31.0+n)));if(rank==0)printf("{\"preflight_status\":%d,\"preflight_change\":%.17g}\n",status,unchanged);MPI_Buffer_detach(&bsend,&bsize);free(bsend);MPI_Finalize();return 0;}
 for(j=1;j<=NY;++j)for(i=1;i<=NX;++i)gp.v[j][i]=gr.v[j][i]=gq.v[j][i]=77.0f;for(n=0;n<nsteps;++n){fixed_signal[n]=-41.0-n;mat_signal[n]=53.0+n;}
 status=visco_sh_reverse_time_adjoint(&cfg,nsteps,bar_receiver,&fixed_terminal.view,&fixed_initial.view,&fixed_scratch.view,fixed_signal);if(status!=0)MPI_Abort(MPI_COMM_WORLD,805);status=visco_sh_reverse_time_adjoint_material(&cfg,nsteps,bar_receiver,&mat_terminal.view,&mat_initial.view,&mat_scratch.view,mat_signal,&material);if(status!=0)MPI_Abort(MPI_COMM_WORLD,806);
 owned=NX*NY;series=(struct visco_sh_material_timestep_vjp_output *)calloc((size_t)nsteps*owned,sizeof(*series));sum=(struct visco_sh_material_timestep_vjp_output *)calloc((size_t)owned,sizeof(*sum));for(k=0;k<5;++k)temp[k]=dg_new();temp_native.g_rhoi=temp[0].v;temp_native.g_mu_x=temp[1].v;temp_native.g_mu_y=temp[2].v;temp_native.g_tau_x=temp[3].v;temp_native.g_tau_y=temp[4].v;{struct visco_sh_full_state *cur=&ref_terminal.view,*prev;for(n=nsteps-1;n>=0;--n){step_cfg=cfg;step_cfg.bar_receiver=bar_receiver+n;memset(&step_material,0,sizeof(step_material));step_material.observable=&trajectory.steps[n];step_material.mu_x=mu_x.v;step_material.tau_x=tau_x.v;step_material.mu_y=mu_y.v;step_material.tau_y=tau_y.v;step_material.reference_sum=refsum;step_material.eta_x=eta;step_material.eta_y=eta;step_material.native_output=&temp_native;prev=(n==0)?&ref_initial.view:((cur==&ref_scratch.view)?&ref_terminal.view:&ref_scratch.view);status=visco_sh_full_state_adjoint_step_material(&step_cfg,cur,prev,ref_signal+n,&step_material);if(status!=0)MPI_Abort(MPI_COMM_WORLD,807);for(j=1;j<=NY;++j)for(i=1;i<=NX;++i){point=(j-1)*NX+i-1;series[n*owned+point].g_rhoi=temp[0].v[j][i];series[n*owned+point].g_mu_x=temp[1].v[j][i];series[n*owned+point].g_mu_y=temp[2].v[j][i];series[n*owned+point].g_tau_x=temp[3].v[j][i];series[n*owned+point].g_tau_y=temp[4].v[j][i];}cur=prev;}}
 if(visco_sh_temporal_native_gradient_accumulate(nsteps,owned,1,series,sum)!=0)MPI_Abort(MPI_COMM_WORLD,808);for(j=1;j<=NY;++j)for(i=1;i<=NX;++i){point=(j-1)*NX+i-1;temp[0].v[j][i]=sum[point].g_rhoi;temp[1].v[j][i]=sum[point].g_mu_x;temp[2].v[j][i]=sum[point].g_mu_y;temp[3].v[j][i]=sum[point].g_tau_x;temp[4].v[j][i]=sum[point].g_tau_y;}if(visco_sh_distributed_material_gradient_vjp(invmat,&mapping,primary.v,rho.v,q.v,&temp_native,rp.v,rr.v,rq.v)!=0)MPI_Abort(MPI_COMM_WORLD,809);
 state_error=state_difference(&fixed_initial,&mat_initial);signal_error=0.0;for(n=0;n<nsteps;++n)signal_error=fmax(signal_error,fabs(fixed_signal[n]-mat_signal[n]));gradient_error=fmax(grad_difference(&gp,&rp),fmax(grad_difference(&gr,&rr),grad_difference(&gq,&rq)));input_after=trajectory_checksum(&trajectory)+fchecksum(&primary)+fchecksum(&rho)+fchecksum(&q)+fchecksum(&rhoi)+fchecksum(&mu_x)+fchecksum(&mu_y)+fchecksum(&tau_x)+fchecksum(&tau_y)+fchecksum(&fipjp)+fchecksum(&f);for(n=0;n<nsteps;++n)input_after+=(n+1)*bar_receiver[n];gradient_checksum=owned_gradient_checksum(&gp,&gr,&gq);if(rank==0)printf("{\"state_error\":%.17g,\"signal_error\":%.17g,\"gradient_error\":%.17g,\"input_change\":%.17g,\"gradient_checksum\":%.17g,\"nsteps\":%d}\n",state_error,signal_error,gradient_error,fabs(input_after-input_before),gradient_checksum,nsteps);
 for(k=0;k<5;++k)dg_free(&temp[k]);free(series);free(sum);visco_sh_material_observable_trajectory_release(&trajectory);MPI_Buffer_detach(&bsend,&bsize);free(bsend);MPI_Finalize();return 0;
}
