"""Positional read_par.c input for the frozen 32x32 physical-Q SH-FWI case.

This is a test fixture, not an application configuration serializer. Records
1--115 are the ordinary solver input and 116--119 are the Q mapping controls.
Optional migration records 120--122 are not used by these MODE=0/1 SH runs.
"""

from pathlib import Path


def write_sh_parameter(
    output: Path, *, mode: int = 0,
    model_prefix: str = "model/true", grad_method: int = 1,
    nprocx: int = 1, nprocy: int = 1, eps_scale: float = 1.0e6,
    stepmax: int = 10, invmat1: int = 1, inv_mod_out: int = 0,
    inv_model_file: str = "model/inverted", itermax: int = 1,
    grad_form: int = 2, grad_filter: int = 0,
) -> None:
    """Write the complete fixture schema in production parser record order.

    Keep even inactive controls explicit: the parser consumes records by
    position, not by label. Values include the old fixture's implicit defaults.
    """
    records = (
        ("MODE", mode),
        ("PHYSICS", 5),
        ("NPROCX", nprocx),
        ("NPROCY", nprocy),
        ("FD_ORDER", 4),
        ("MAX_RELATIVE_ERROR", 0),
        ("NX", 32),
        ("NY", 32),
        ("DH", 10.0),
        ("TIME", 0.08),
        ("DT", 0.0005),
        ("QUELLART", 1),
        ("SIGNAL_FILE", "source/signal.dat"),
        ("TS", 0.0),
        ("SRCREC", 1),
        ("SOURCE_FILE", "source/one.dat"),
        ("RUN_MULTIPLE_SHOTS", 1),
        ("FC_SPIKE_1", 0.0),
        ("FC_SPIKE_2", 0.0),
        ("ORDER_SPIKE", 2),
        ("WRITE_STF", 0),
        ("READMOD", 1),
        ("MFILE", model_prefix),
        ("WRITEMOD", 1),
        ("L", 1),
        ("FL", 20.0),
        ("TAU", 1.0),
        ("FREE_SURF", 0),
        ("FW", 6),
        ("DAMPING", 2000.0),
        ("FPML", 20.0),
        ("NPOWER", 2.0),
        ("K_MAX_PML", 1.0),
        ("BOUNDARY", 0),
        ("SNAP", 0),
        ("SNAP_SHOT", 1),
        ("TSNAP1", 0.0),
        ("TSNAP2", 0.0),
        ("TSNAPINC", 0.0),
        ("IDX", 1),
        ("IDY", 1),
        ("SNAP_FORMAT", 3),
        ("SNAP_FILE", "snap/field"),
        ("SEISMO", 1),
        ("READREC", 1),
        ("REC_FILE", "receiver/line"),
        ("REFREC", "0.0, 0.0"),
        ("N_STREAMER", 0),
        ("REC_INCR_X", 80),
        ("REC_INCR_Y", 0),
        ("NDT", 1),
        ("SEIS_FORMAT", 1),
        ("SEIS_FILE_VX", "su/unused_x.su"),
        ("SEIS_FILE_VY", "su/observed_y.su"),
        ("SEIS_FILE_CURL", "su/unused_curl.su"),
        ("SEIS_FILE_DIV", "su/unused_div.su"),
        ("SEIS_FILE_P", "su/unused_p.su"),
        ("LOG_FILE", "log/denise"),
        ("LOG", 1),
        ("ITERMAX", itermax),
        ("JACOBIAN", "jacobian/unused"),
        ("DATA_DIR", "su/observed"),
        ("TAPER", 0),
        ("TAPERLENGTH", 1),
        ("GRADT", "1, 1, 1, 1"),
        ("INVMAT1", invmat1),
        ("GRAD_FORM", grad_form),
        ("QUELLTYPB", 2),
        ("TESTSHOTS", "1, 1, 1"),
        ("SWS_TAPER_GRAD_VERT", 0),
        ("SWS_TAPER_GRAD_HOR", 0),
        ("EXP_TAPER_GRAD_HOR", 1.0),
        ("SWS_TAPER_GRAD_SOURCES", 0),
        ("SWS_TAPER_CIRCULAR_PER_SHOT", 0),
        ("SRTSHAPE", 1),
        ("SRTRADIUS", 50.0),
        ("FILTSIZE", 1),
        ("SWS_TAPER_FILE", 0),
        ("TFILE", "taper/unused"),
        ("INV_MOD_OUT", inv_mod_out),
        ("INV_MODELFILE", inv_model_file),
        ("VPUPPERLIM", 5000.0),
        ("VPLOWERLIM", 100.0),
        ("VSUPPERLIM", 5000.0),
        ("VSLOWERLIM", 100.0),
        ("RHOUPPERLIM", 5000.0),
        ("RHOLOWERLIM", 100.0),
        ("QSUPPERLIM", 100.0),
        ("QSLOWERLIM", 10.0),
        ("GRAD_METHOD", grad_method),
        ("PCG_BETA", 1),
        ("NLBFGS", 1),
        ("MODEL_FILTER", 0),
        ("FILT_SIZE", 1),
        ("DTINV", 1),
        # Raw Q gradients here are O(1e-7); retain the accepted B5A fixture
        # scale making its first trial visible above float resolution at Q=70.
        ("EPS_SCALE", eps_scale),
        ("STEPMAX", stepmax),
        ("SCALEFAC", 2.0),
        ("TRKILL", 0),
        ("TRKILL_FILE", "tracekill/unused"),
        ("PICKS_FILE", "picks/unused"),
        ("MISFIT_LOG_FILE", "log/misfit"),
        ("MIN_ITER", 1),
        ("GRAD_FILTER", grad_filter),
        ("FILT_SIZE_GRAD", 1),
        ("TIMELAPSE", 0),
        ("DATA_DIR_T0", "su/CAES_spike_time_0/DENISE_CAES"),
        ("RTMOD", 0),
        ("GRAVITY", 0),
        ("NGRAVB", 500),
        ("NZGRAV", 200000),
        ("GRAV_TYPE", 1),
        ("BACK_DENSITY", 2),
        ("DFILE", "gravity/background_density.rho"),
        ("RTM_SHOT", 0),
        ("Q_PARAMETERIZATION_MODE", 1),
        ("Q_APPROX_FMIN", 5.0),
        ("Q_APPROX_FMAX", 40.0),
        ("Q_APPROX_DF", 1.0),
    )
    assert len(records) == 119
    assert len({name for name, _ in records}) == len(records)
    output.write_text(
        "# Frozen ephemeral physical-Q SH-FWI fixture: read_par.c records 1--119\n"
        + "".join(f"({name}) = {value}\n" for name, value in records),
        encoding="ascii", newline="\n",
    )
